/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import hotel.Habitacion;
import hotel.Huesped;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import registro.conexion;

/**
 *
 * @author nicolaita
 */
public class buscarCliente extends javax.swing.JFrame {

    /**
     * Creates new form buscarCliente
     */
    public buscarCliente() {

        initComponents();
        /**
         * Coloca la pestaña en el centro de la pantalla al iniciar
         */
        this.setLocationRelativeTo(null);
        /**
         * Icono de aplicación
         */
        setIconImage(new ImageIcon(getClass().getResource("/Logo/faroLogo.png")).getImage());
        /**
         * Pone oculto el mensaje "Rut no valido."
         */
        labelAvisoRut.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAvisoRut = new javax.swing.JLabel();
        butMinimizarBuscar = new javax.swing.JButton();
        butXBuscar = new javax.swing.JButton();
        butCancelarBuscar = new javax.swing.JButton();
        labelTitulo = new javax.swing.JLabel();
        butBuscar = new javax.swing.JButton();
        txtBuscarRut = new javax.swing.JTextField();
        labelRut = new javax.swing.JLabel();
        labelLogo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBoleta = new javax.swing.JTextArea();
        buscarBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelAvisoRut.setForeground(new java.awt.Color(255, 204, 51));
        labelAvisoRut.setText("Rut no valido.");
        getContentPane().add(labelAvisoRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 80, 80, -1));

        butMinimizarBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/minimizar2.png"))); // NOI18N
        butMinimizarBuscar.setBorder(null);
        butMinimizarBuscar.setBorderPainted(false);
        butMinimizarBuscar.setContentAreaFilled(false);
        butMinimizarBuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/minimizar1.png"))); // NOI18N
        butMinimizarBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butMinimizarBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(butMinimizarBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 20, 40));

        butXBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/xx1.png"))); // NOI18N
        butXBuscar.setBorder(null);
        butXBuscar.setBorderPainted(false);
        butXBuscar.setContentAreaFilled(false);
        butXBuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/xx2.png"))); // NOI18N
        butXBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butXBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(butXBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, -1, 20));

        butCancelarBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/cancelarRegistro.png"))); // NOI18N
        butCancelarBuscar.setBorder(null);
        butCancelarBuscar.setBorderPainted(false);
        butCancelarBuscar.setContentAreaFilled(false);
        butCancelarBuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/cancelarRegistro2.png"))); // NOI18N
        butCancelarBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCancelarBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(butCancelarBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 670, -1, -1));

        labelTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 204, 51));
        labelTitulo.setText("BUSCAR CLIENTES");
        getContentPane().add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        butBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/buscarCliente1.png"))); // NOI18N
        butBuscar.setBorder(null);
        butBuscar.setBorderPainted(false);
        butBuscar.setContentAreaFilled(false);
        butBuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/buscarCliente2.png"))); // NOI18N
        butBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(butBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 88, 150, 50));

        txtBuscarRut.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtBuscarRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 240, -1));

        labelRut.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelRut.setForeground(new java.awt.Color(255, 255, 255));
        labelRut.setText("Rut:");
        getContentPane().add(labelRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/faroLogoTrans.png"))); // NOI18N
        getContentPane().add(labelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        txtBoleta.setBackground(new java.awt.Color(255, 255, 255));
        txtBoleta.setColumns(20);
        txtBoleta.setRows(5);
        txtBoleta.setEditable(false);
        jScrollPane1.setViewportView(txtBoleta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 450, 510));

        buscarBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/buscarClientes.png"))); // NOI18N
        buscarBG.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                buscarBGMouseDragged(evt);
            }
        });
        buscarBG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buscarBGMousePressed(evt);
            }
        });
        getContentPane().add(buscarBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Boton de "X" que cierra la ventana y abre el menú
     *
     * @param evt
     */
    private void butXBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butXBuscarActionPerformed
        this.dispose();
        menuSys menu1 = new menuSys();
        menu1.setVisible(true);
    }//GEN-LAST:event_butXBuscarActionPerformed
    /**
     * Boton que minimiza la ventana
     *
     * @param evt
     */
    private void butMinimizarBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butMinimizarBuscarActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_butMinimizarBuscarActionPerformed
    /**
     * Boton que cierra la ventana y abre el menú
     *
     * @param evt
     */
    private void butCancelarBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCancelarBuscarActionPerformed
        this.dispose();
        menuSys menu1 = new menuSys();
        menu1.setVisible(true);
    }//GEN-LAST:event_butCancelarBuscarActionPerformed

    /**
     * Botón que busca un rut e imprime la boleta respectiva del cliente, en el
     * caso de que el rut sea invalido manda mensaje "Huesped No encontrado."
     *
     * @param evt
     */
    private void butBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBuscarActionPerformed

        try {
            conexion con = new conexion();
            Huesped huesped = con.buscar(txtBuscarRut.getText());
            Habitacion habitacion = con.buscarHabitacion(txtBuscarRut.getText());

            if (huesped.getNombre() != null) {
                txtBoleta.setText("====== información del Huesped ======\n\n"
                        + "rut: " + huesped.getRut() + "\n"
                        + "nombre: " + huesped.getNombre() + " " + huesped.getApellido() + "\n"
                        + "edad: " + huesped.getEdad() + "\n"
                        + "sexo: " + huesped.getSexo() + "\n"
                        + "pais: " + huesped.getPais() + "\n"
                        + "tipo huesped: " + huesped.getTipoHuesped() + "\n"
                        + "correo: " + huesped.getCorreo() + "\n"
                        + "Telefono: " + huesped.getNumeroTelefono() + "\n"
                        + "Acompañantes: " + huesped.getAcompannantes() + "\n"
                        + "====== información de la estadía ======\n\n"
                        + "Numero de Habitacion: " + habitacion.getNumeroHabitacion() + "\n"
                        + "tipo de habitacion: " + habitacion.getTipoHabitacion() + "\n"
                        + "cantidad de dias: " + habitacion.getCantidadDias() + "\n"
                        + "fecha de inicio: " + habitacion.getFechaInicio() + "\n"
                        + "fecha de termino: " + habitacion.getFechaTermino());
            } else {
                JOptionPane.showMessageDialog(this, "Huesped No encontrado.");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }


    }//GEN-LAST:event_butBuscarActionPerformed
    /**
     * Se define xx e yy como cordenadas de mouse
     */
    int xx, xy;

    /**
     * Toma las coordenadas del mouse presionado
     *
     * @param evt
     */
    private void buscarBGMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarBGMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_buscarBGMousePressed
    /**
     * Se toman las cordenadas del mouse dragged esto genera que la ventana se
     * pueda mover con el mouse
     *
     * @param evt
     */
    private void buscarBGMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarBGMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        setLocation(x - xx, y - xy);
    }//GEN-LAST:event_buscarBGMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buscarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buscarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buscarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buscarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buscarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buscarBG;
    private javax.swing.JButton butBuscar;
    private javax.swing.JButton butCancelarBuscar;
    private javax.swing.JButton butMinimizarBuscar;
    private javax.swing.JButton butXBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAvisoRut;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelRut;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextArea txtBoleta;
    private javax.swing.JTextField txtBuscarRut;
    // End of variables declaration//GEN-END:variables
}
