/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author nicolaita
 */
public class cerrarSesion extends javax.swing.JDialog {

    /**
     * Creates new form cerrarSesion
     */
    public cerrarSesion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        /**
         * Coloca la pestaña en el centro de la pantalla al iniciar
         */
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cerrarNo = new javax.swing.JButton();
        cerrarSi = new javax.swing.JButton();
        butCerrarDialog = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cerrarNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/NO1.png"))); // NOI18N
        cerrarNo.setBorder(null);
        cerrarNo.setBorderPainted(false);
        cerrarNo.setContentAreaFilled(false);
        cerrarNo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/NO2.png"))); // NOI18N
        cerrarNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarNoActionPerformed(evt);
            }
        });
        getContentPane().add(cerrarNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, 30));

        cerrarSi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/SI1.png"))); // NOI18N
        cerrarSi.setBorder(null);
        cerrarSi.setBorderPainted(false);
        cerrarSi.setContentAreaFilled(false);
        cerrarSi.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/SI2.png"))); // NOI18N
        cerrarSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSiActionPerformed(evt);
            }
        });
        getContentPane().add(cerrarSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 100, 30));

        butCerrarDialog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/xx3.png"))); // NOI18N
        butCerrarDialog.setBorder(null);
        butCerrarDialog.setBorderPainted(false);
        butCerrarDialog.setContentAreaFilled(false);
        butCerrarDialog.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/xx1.png"))); // NOI18N
        butCerrarDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCerrarDialogActionPerformed(evt);
            }
        });
        getContentPane().add(butCerrarDialog, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/cerrarSesion.png"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Botón que cierra el dialog y no hace nada
     *
     * @param evt
     */
    private void butCerrarDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCerrarDialogActionPerformed
        this.dispose();
        menuSys Sys1 = new menuSys();
        Sys1.setVisible(true);
    }//GEN-LAST:event_butCerrarDialogActionPerformed
    /**
     * Botón que cierra el dialog y no hace nada
     *
     * @param evt
     */
    private void cerrarNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarNoActionPerformed
        this.dispose();
        menuSys Sys1 = new menuSys();
        Sys1.setVisible(true);
    }//GEN-LAST:event_cerrarNoActionPerformed
    /**
     * Botón que cierra el dialog y cierra la seción
     *
     * @param evt
     */
    private void cerrarSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSiActionPerformed
        this.dispose();
        iniSys sys = new iniSys();
        sys.setVisible(true);


    }//GEN-LAST:event_cerrarSiActionPerformed
    /**
     * Coordenadas de mouse y ventana para poder arrastrarla
     */
    int xx, xy;

    /**
     * Toma las coordenadas del mouse presionado
     *
     * @param evt
     */
    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed
    /**
     * Se toman las cordenadas del mouse dragged esto genera que la ventana se
     * pueda mover con el mouse
     *
     * @param evt
     */
    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jLabel1MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cerrarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cerrarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cerrarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cerrarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                cerrarSesion dialog = new cerrarSesion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butCerrarDialog;
    private javax.swing.JButton cerrarNo;
    private javax.swing.JButton cerrarSi;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
