/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import hotel.Habitacion;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import registro.conexion;

/**
 *
 * @author nicolaita
 */
public class eliminarCliente extends javax.swing.JFrame {

    /**
     * Creates new form eliminarCliente
     */
    public eliminarCliente() {
        initComponents();
        /**
         * Coloca la pestaña en el centro de la pantalla al iniciar
         */
        this.setLocationRelativeTo(null);
        /**
         * Icono de aplicación
         */
        setIconImage(new ImageIcon(getClass().getResource("/Logo/faroLogo.png")).getImage());
        /**
         * Oculta mensaje "Rut no valido."
         */
        labelMensaje1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butAtrasEliminar = new javax.swing.JButton();
        txtEliminarRut = new javax.swing.JTextField();
        butEliminar = new javax.swing.JButton();
        botonMinimizar = new javax.swing.JButton();
        botonCerrar = new javax.swing.JButton();
        labelMensaje1 = new javax.swing.JLabel();
        labelEtiquetaRut = new javax.swing.JLabel();
        eliminacionBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        butAtrasEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/atras1.png"))); // NOI18N
        butAtrasEliminar.setBorder(null);
        butAtrasEliminar.setBorderPainted(false);
        butAtrasEliminar.setContentAreaFilled(false);
        butAtrasEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/atras2.png"))); // NOI18N
        butAtrasEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAtrasEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(butAtrasEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        txtEliminarRut.setBackground(new java.awt.Color(255, 255, 255));
        txtEliminarRut.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(txtEliminarRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 380, 40));

        butEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/eliminar1.png"))); // NOI18N
        butEliminar.setToolTipText("");
        butEliminar.setBorder(null);
        butEliminar.setBorderPainted(false);
        butEliminar.setContentAreaFilled(false);
        butEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/eliminar2.png"))); // NOI18N
        butEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(butEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));

        botonMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/minimizar2.png"))); // NOI18N
        botonMinimizar.setBorder(null);
        botonMinimizar.setBorderPainted(false);
        botonMinimizar.setContentAreaFilled(false);
        botonMinimizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/minimizar1.png"))); // NOI18N
        botonMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMinimizarActionPerformed(evt);
            }
        });
        getContentPane().add(botonMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 20, 20));

        botonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/xx1.png"))); // NOI18N
        botonCerrar.setBorder(null);
        botonCerrar.setBorderPainted(false);
        botonCerrar.setContentAreaFilled(false);
        botonCerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/xx2.png"))); // NOI18N
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(botonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, -1, -1));

        labelMensaje1.setForeground(new java.awt.Color(255, 204, 102));
        labelMensaje1.setText("Rut o pasaporte no valido.");
        getContentPane().add(labelMensaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 240, -1));

        labelEtiquetaRut.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelEtiquetaRut.setForeground(new java.awt.Color(255, 255, 255));
        labelEtiquetaRut.setText("RUT:");
        getContentPane().add(labelEtiquetaRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 60, 20));

        eliminacionBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/eliminarPane1.png"))); // NOI18N
        eliminacionBG.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                eliminacionBGMouseDragged(evt);
            }
        });
        eliminacionBG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eliminacionBGMousePressed(evt);
            }
        });
        getContentPane().add(eliminacionBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Botón que cierra la ventana y abre el menu principal
     *
     * @param evt
     */
    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        this.dispose();
        this.dispose();
        menuSys menu2 = new menuSys();
        menu2.setVisible(true);

    }//GEN-LAST:event_botonCerrarActionPerformed
    /**
     * Botón que minimiza la ventana
     *
     * @param evt
     */
    private void botonMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMinimizarActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_botonMinimizarActionPerformed

    /**
     * Botón que confirma que el rut esté en la base de datos, si es true abre
     * un JDialog de confirmacion de eliminación
     *
     * @param evt
     */
    private void butEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butEliminarActionPerformed
        try {
            int cancelButton = JOptionPane.showConfirmDialog(
                    null,
                    "¿Seguro que quieres eliminar al huesped?",
                    "ADVERTENCIA",
                    JOptionPane.YES_NO_OPTION);
            if (cancelButton == JOptionPane.YES_OPTION) {
                conexion con = new conexion();
                Habitacion habitacion1 = con.buscarHabitacion(txtEliminarRut.getText());

                //cuando se elimina un cliente, se cambia el estado de una habitacion
                habitacion1.setDisponibilidad(true);
                habitacion1.setFechaInicio("----");
                habitacion1.setFechaTermino("----");
                habitacion1.setCantidadDias("0");

                //paso los datos cambiados a la base de datos
                con.estadoHabitacion(habitacion1);

                if (con.eliminarRutBoleta(txtEliminarRut.getText()) != 0 && con.eliminarRut(txtEliminarRut.getText()) != 0) {

                    JOptionPane.showMessageDialog(this, "Huesped Eliminado");
                    txtEliminarRut.setText("");

                } else {
                    JOptionPane.showMessageDialog(this, "Huesped No Eliminado. Pueda que el rut no sea correcto");
                    txtEliminarRut.setText("");

                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_butEliminarActionPerformed
    /**
     * Se define xx e yy como cordenadas de mouse
     */
    int xx, xy;

    /**
     * Toma las coordenadas del mouse presionado
     *
     * @param evt
     */
    private void eliminacionBGMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminacionBGMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_eliminacionBGMousePressed
    /**
     * Se toman las cordenadas del mouse dragged esto genera que la ventana se
     * pueda mover con el mouse
     *
     * @param evt
     */
    private void eliminacionBGMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminacionBGMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        setLocation(x - xx, y - xy);
    }//GEN-LAST:event_eliminacionBGMouseDragged
    /**
     * Botón que cierra la ventana y abre el menu principal
     *
     * @param evt
     */
    private void butAtrasEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAtrasEliminarActionPerformed
        menuSys menu = new menuSys();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_butAtrasEliminarActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(eliminarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(eliminarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(eliminarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(eliminarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new eliminarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonCerrar;
    public javax.swing.JButton botonMinimizar;
    public javax.swing.JButton butAtrasEliminar;
    public javax.swing.JButton butEliminar;
    public javax.swing.JLabel eliminacionBG;
    public javax.swing.JLabel labelEtiquetaRut;
    public javax.swing.JLabel labelMensaje1;
    public javax.swing.JTextField txtEliminarRut;
    // End of variables declaration//GEN-END:variables
}
