/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author nicolaita
 */
public class iniOlvido extends javax.swing.JDialog {

    /**
     * Creates new form iniOlvido
     */
    public iniOlvido(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        /**
         * Coloca la pestaña en el centro de la pantalla al iniciar
         */
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butAceptarOlvido = new javax.swing.JButton();
        butCerrarOlvido = new javax.swing.JButton();
        OlvidoPANE = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        butAceptarOlvido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/ACEPTOlvi1.png"))); // NOI18N
        butAceptarOlvido.setBorder(null);
        butAceptarOlvido.setBorderPainted(false);
        butAceptarOlvido.setContentAreaFilled(false);
        butAceptarOlvido.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/ACEPTOlvi2.png"))); // NOI18N
        butAceptarOlvido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAceptarOlvidoActionPerformed(evt);
            }
        });
        getContentPane().add(butAceptarOlvido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 110, 40));

        butCerrarOlvido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/xx3.png"))); // NOI18N
        butCerrarOlvido.setBorder(null);
        butCerrarOlvido.setBorderPainted(false);
        butCerrarOlvido.setContentAreaFilled(false);
        butCerrarOlvido.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/xx1.png"))); // NOI18N
        butCerrarOlvido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCerrarOlvidoActionPerformed(evt);
            }
        });
        getContentPane().add(butCerrarOlvido, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 30, 30));

        OlvidoPANE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/olvidoPane.png"))); // NOI18N
        OlvidoPANE.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                OlvidoPANEMouseDragged(evt);
            }
        });
        OlvidoPANE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                OlvidoPANEMousePressed(evt);
            }
        });
        getContentPane().add(OlvidoPANE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Botón en forma de "x" que cierra el JDialog
     *
     * @param evt
     */
    private void butCerrarOlvidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCerrarOlvidoActionPerformed
        this.dispose();
    }//GEN-LAST:event_butCerrarOlvidoActionPerformed
    /**
     * Botón de aceptar que cierra el JDialog
     *
     * @param evt
     */
    private void butAceptarOlvidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAceptarOlvidoActionPerformed
        this.dispose();
    }//GEN-LAST:event_butAceptarOlvidoActionPerformed
    /**
     * Coordenadas de mouse y ventana para poder arrastrarla
     */
    int xx, xy;

    /**
     * Toma las coordenadas del mouse presionado
     *
     * @param evt
     */
    private void OlvidoPANEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OlvidoPANEMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_OlvidoPANEMousePressed
    /**
     * Se toman las cordenadas del mouse dragged esto genera que la ventana se
     * pueda mover con el mouse
     *
     * @param evt
     */
    private void OlvidoPANEMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OlvidoPANEMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        setLocation(x - xx, y - xy);
    }//GEN-LAST:event_OlvidoPANEMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(iniOlvido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(iniOlvido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(iniOlvido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(iniOlvido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                iniOlvido dialog = new iniOlvido(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel OlvidoPANE;
    private javax.swing.JButton butAceptarOlvido;
    private javax.swing.JButton butCerrarOlvido;
    // End of variables declaration//GEN-END:variables
}
