/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author nicolaita
 */
public class menuSys extends javax.swing.JFrame {

    /**
     * Creates new form menuSys
     */
    public menuSys() {
        initComponents();
        /**
         * Coloca la pestaña en el centro de la pantalla al iniciar
         */
        this.setLocationRelativeTo(null);
        /**
         * Icono de aplicación
         */
        setIconImage(new ImageIcon(getClass().getResource("/Logo/faroLogo.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnListarClientes = new javax.swing.JButton();
        btnEliminarClientes = new javax.swing.JButton();
        btnRegistroClienteMenu = new javax.swing.JButton();
        butMinMenuSys = new javax.swing.JButton();
        cerrarSys1 = new javax.swing.JButton();
        btnVerClientes = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        menuSys = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnListarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/listaClientes1.png"))); // NOI18N
        btnListarClientes.setBorder(null);
        btnListarClientes.setBorderPainted(false);
        btnListarClientes.setContentAreaFilled(false);
        btnListarClientes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/listaClientes2.png"))); // NOI18N
        btnListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarClientesActionPerformed(evt);
            }
        });
        getContentPane().add(btnListarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 50));

        btnEliminarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/eliminarClientes1.png"))); // NOI18N
        btnEliminarClientes.setBorder(null);
        btnEliminarClientes.setBorderPainted(false);
        btnEliminarClientes.setContentAreaFilled(false);
        btnEliminarClientes.setRolloverEnabled(true);
        btnEliminarClientes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/eliminarClientes2.png"))); // NOI18N
        btnEliminarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClientesActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 50));

        btnRegistroClienteMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/registrarClientes1.png"))); // NOI18N
        btnRegistroClienteMenu.setBorder(null);
        btnRegistroClienteMenu.setBorderPainted(false);
        btnRegistroClienteMenu.setContentAreaFilled(false);
        btnRegistroClienteMenu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/registrarClientes2.png"))); // NOI18N
        btnRegistroClienteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroClienteMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistroClienteMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 50));

        butMinMenuSys.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/minimizar2.png"))); // NOI18N
        butMinMenuSys.setBorder(null);
        butMinMenuSys.setBorderPainted(false);
        butMinMenuSys.setContentAreaFilled(false);
        butMinMenuSys.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/minimizar1.png"))); // NOI18N
        butMinMenuSys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butMinMenuSysActionPerformed(evt);
            }
        });
        getContentPane().add(butMinMenuSys, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, -1, 20));

        cerrarSys1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/xx1.png"))); // NOI18N
        cerrarSys1.setBorder(null);
        cerrarSys1.setBorderPainted(false);
        cerrarSys1.setContentAreaFilled(false);
        cerrarSys1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/xx2.png"))); // NOI18N
        cerrarSys1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarSys1ActionPerformed(evt);
            }
        });
        getContentPane().add(cerrarSys1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, -1, -1));

        btnVerClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/verClientes1.png"))); // NOI18N
        btnVerClientes.setBorder(null);
        btnVerClientes.setBorderPainted(false);
        btnVerClientes.setContentAreaFilled(false);
        btnVerClientes.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/verClientes2.png"))); // NOI18N
        btnVerClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerClientesActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, 50));

        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/cerrarSesion1.png"))); // NOI18N
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setContentAreaFilled(false);
        btnCerrarSesion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/cerrarSesion2.png"))); // NOI18N
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, 50));

        menuSys.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/SYS1.png"))); // NOI18N
        menuSys.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                menuSysMouseDragged(evt);
            }
        });
        menuSys.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuSysMousePressed(evt);
            }
        });
        getContentPane().add(menuSys, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Se define xx e yy como cordenadas de mouse
     */
    int xx, xy;

    /**
     * Toma las coordenadas del mouse presionado
     *
     * @param evt
     */
    private void menuSysMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSysMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_menuSysMousePressed
    /**
     * Se toman las cordenadas del mouse dragged esto genera que la ventana se
     * pueda mover con el mouse
     *
     * @param evt
     */
    private void menuSysMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSysMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        setLocation(x - xx, y - xy);
    }//GEN-LAST:event_menuSysMouseDragged
    /**
     * Botón de "x" que cierra la sesión y abre el inicio de sesión
     *
     * @param evt
     */
    private void cerrarSys1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarSys1ActionPerformed
        this.dispose();
        cerrarSesion hijo = new cerrarSesion(this, true);
        hijo.setVisible(true);

    }//GEN-LAST:event_cerrarSys1ActionPerformed
    /**
     * Botón para minimizar ventana
     *
     * @param evt
     */
    private void butMinMenuSysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butMinMenuSysActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_butMinMenuSysActionPerformed
    /**
     * Botón que abre el manu para ingresar datos del cliente, abre
     * IngresoCliente
     *
     * @param evt
     */
    private void btnRegistroClienteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroClienteMenuActionPerformed
        registroMenu but1 = new registroMenu();
        but1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistroClienteMenuActionPerformed
    /**
     * Botón que cierra la sesión, cerrando el menú y abirendo la pantalla
     * inicial de inicio de seción (iniSys)
     *
     * @param evt
     */
    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        this.dispose();
        cerrarSesion hijo = new cerrarSesion(this, true);
        hijo.setVisible(true);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed
    /**
     * Botón que cierra el menú y abre la ventana de eliminar clientes
     * (eliminarCliente)
     *
     * @param evt
     */
    private void btnEliminarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClientesActionPerformed
        eliminarCliente eliminar1 = new eliminarCliente();
        eliminar1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEliminarClientesActionPerformed
    /**
     * Botón que cierra el menú y abre la ventana de ver clientes
     * (buscarCliente)
     *
     * @param evt
     */
    private void btnVerClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerClientesActionPerformed
        buscarCliente buscar1 = new buscarCliente();
        buscar1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVerClientesActionPerformed
    /**
     * Botón que cierra el menú y abre la ventana de listar clientes
     * (listaDeClientes)
     *
     * @param evt
     */
    private void btnListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarClientesActionPerformed
        listaDeClientes cliente1 = new listaDeClientes();
        cliente1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListarClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuSys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuSys().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnEliminarClientes;
    private javax.swing.JButton btnListarClientes;
    private javax.swing.JButton btnRegistroClienteMenu;
    private javax.swing.JButton btnVerClientes;
    private javax.swing.JButton butMinMenuSys;
    private javax.swing.JButton cerrarSys1;
    private javax.swing.JLabel menuSys;
    // End of variables declaration//GEN-END:variables
}
